### ISSUE TITLE
CRUD Users 

### ISSUE THREAD

**Issue by SandraMarcelaHerreraArriaga** [desarrolladorSLP/technovationslp-management-app-react#3]
Users must have:

- Name
- email
- phone number

** Add mockup for screen(s) for CRUD operation

**Comment by ulises-lara** [comment]
Closing this issue, the mockups that we will be using for this project are the same as the existing Angular app.
The mockups can be found at:
https://github.com/desarrolladorSLP/technovationslp-management-app/issues/2
